dist: trusty
sudo: required

language:
  - cpp
compiler:
  - clang

script:
  # Check versions of gcc, g++ and cmake
  - clang --version && clang++ --version && cmake --version
  # Run your build commands next
  - cd build
  - CC=clang CXX=clang++ cmake ../source
  - make