dist: trusty
sudo: required

language:
  - cpp
compiler:
  - clang

before_install:
  - sudo apt-get install libboost-dev
  - sudo apt-get install libgtk2.0-dev

script:
  # Check versions of gcc, g++ and cmake
  - clang --version && clang++ --version && cmake --version
  # Run your build commands next
  - cd build
  - CC=clang CXX=clang++ cmake ../source
  - make