language:
  - cpp
compiler:
  - clang

script:
  # Export CC and CXX to tell cmake which compiler to use
  - export CC=/usr/bin/gcc-6
  - export CXX=/usr/bin/g++-6
  # Check versions of gcc, g++ and cmake
  - clang --version && clang++ --version && cmake --version
  # Run your build commands next
  - cd build
  - CC=clang CXX=clang++ cmake ../source
  - make